import type { Metadata } from "next";
import "./globals.css";
import AuthProvider from "./config/authProvider";

export const metadata: Metadata = {
  title: "O3VET - OZONIOTERAPIA VETERINÁRIA",
  description: "Generated by create next app",
  icons: "./favicon.ico",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
